app.name=NauJava
app.version=1.0.0

management.endpoints.web.exposure.include=*
spring.jmx.enabled=true
management.endpoints.jmx.exposure.include=*
spring.jmx.default-domain=ru.alinacozy.NauJava

spring.datasource.url=jdbc:postgresql://localhost:5432/flossdb
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



